config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :profiles

  resources :artworks

  resources :images, only: [:create, :update, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :purchases, only: [:new, :create]

  resources :refunds, only: [:create]

  resources :dashboards, only: :show

  authenticated :user do
    root 'dashboards#show', as: :authenticated_root # change root for signed-in users
  end

  get 'welcome/about'

  root 'welcome#index'

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :user
  has_many :purchases
  has_many :favorites, dependent: :destroy
  has_many :images, -> {order(position: :asc)}, as: :imageable, dependent: :destroy
  # accepts_attachments_for :images, attachment: :file, append: true
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true

  def category_list
    category.join(', ')
  end

  def category_list=(category)
    self.category = category.split(',')
  end
end

app/models/dashboard.rb
class Dashboard

  def initialize(user)
    @user = user
  end

  def listed_artworks
    @user.artworks.all
  end

  def purchased_artworks
    @user.purchased_artworks.all
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  attachment :file
  acts_as_list scope: :imageable
  # default_scope { order(:position) }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :favorites, as: :favoritable, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :artwork
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]

  has_one :profile
  has_many :artworks
  has_many :purchases
  has_many :purchased_artworks, through: :purchases, source: :artwork
  has_many :favorites, dependent: :destroy

  # def favorite_for(favoritable)
  #   favorites.where(favoritable_id: favoritable.id).first
  # end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController

  def index
    @artworks = Artwork.all
  end

  def show
    @artwork   = Artwork.find(params[:id])
    @favorited = current_user.favorites.find_by(favoritable: @artwork)
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = current_user.artworks.new(artwork_params)

    if @artwork.save!
      flash[:notice] = "Artwork saved successfully"
      redirect_to artwork_path(@artwork.id)
    else
      flash[:alert] = "There was an error saving your artwork."
      redirect_to new_artwork_path
    end
  end

  def edit
    @artwork = Artwork.find(params[:id])
  end

  def update
    @artwork = Artwork.find(params[:id])

    if @artwork.update(artwork_params)
      flash[:notice] = "Artwork saved successfully"
      redirect_to artwork_path
    else
      flash[:alert] = "There was an error saving your artwork."
      redirect_to new_artwork_path
    end
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :category_list, :description, :price, :discount,
      images_attributes:[:id, :file, :_destroy])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def update
    # use 'acts_as_list' gem helper 'insert_at' to update image position
    image = Image.find(params[:id])
    image.insert_at(params[:image][:position].to_i)
    redirect_to :back
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile   = Profile.find(params[:id])
    @favorited = Favorite.find_by(favoritable: @profile, user: current_user)
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params) # syntax for has_one association

    if @profile.save!
      flash[:notice] = "profile saved"
      redirect_to profile_path(@profile)
    else
      flash[:alert] = "Error saving profile"
      redirect_to new_profile_path
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      flash[:notice] = "profile updated"
      redirect_to @profile
    else
      flash[:alert] = "Error updating profile"
      redirect_to edit_profile_path
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :tagline, :statement, :info,
      images_attributes:[:id, :file, :_destroy])
  end
end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController

  def create
    # binding.pry
    @purchase = Purchase.find(params[:purchase_id])
    Stripe::Refund.create(charge: @purchase.charge_id)
    @purchase.update(refunded: true)

    flash[:notice] = "Your refund has been issued"
    redirect_to root_path

  rescue Stripe::InvalidRequestError => e
     flash[:alert] = e.message
     redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # helper method for displaying gravatar image
  def gravatar_url(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, class: "gravatar")
  end

  # helper method to display errors on forms
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def authorize_view_element
    current_user.admin? || (current_user.premium? && @wiki.user_id = current_user.id)
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/refunds_helper.rb
module RefundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artworks/_image_fields.html.haml
-# .nested-fields
-#   = f.attachment_field :file
-#   %br/
-#   = link_to_remove_association 'remove image', f

app/views/artworks/edit.html.haml
%h1 Edit your Artwork Listing
%br/
%center
  .list-group#draggableList
    - @artwork.images.each do |img|
      = div_for(img, class: 'list-group-item') do
        = image_tag(attachment_url(img, :file, :fit, 400, 400))
        %span{ class: 'ion-arrow-move', 'aria-hidden' => 'true' }

.col-md-8
  = form_for @artwork do |f|
    = form_group_tag(@artwork.errors[:title]) do
      = f.label :title
      = f.text_field :title, class: 'form-control',
        placeholder: "Enter the title of your piece here"

    = form_group_tag(@artwork.errors[:category]) do
      = f.label :category
      = f.text_field :category_list, class: 'form-control',
        placeholder: "Enter a category/categories e.g. Landscapes, separated by commas"

    = form_group_tag(@artwork.errors[:description]) do
      = f.label :description
      = f.text_area :description, rows: 4, class: 'form-control',
        placeholder:  "Enter a brief description of your piece here"

    = form_group_tag(@artwork.errors[:price]) do
      = f.label :price
      = f.number_field :price, class: 'form-control form-narrow',
        placeholder: "Enter a price in USD here"

    = form_group_tag(@artwork.errors[:discount]) do
      = f.label :discount
      = f.number_field :discount, class: 'form-control form-narrow',
        placeholder: "Enter an optional discount % here"

    %h3 Images
    #images
      = f.fields_for :images do |image|
        = render 'shared/image_fields', f: image
      .links
        = link_to_add_association 'add image', f, :images, partial: 'shared/image_fields'
    %br/
    = f.submit "Save", class: 'btn btn-success'

app/views/artworks/index.html.haml
%h1 Discover great Artwork on Easel
%br/
%center
  - @artworks.each do |artwork|
    = link_to image_tag(attachment_url(artwork.images.first, :file, :fill, 200, 200),
      class: 'image-responsive'), artwork_path(artwork)
  -# - @artworks.in_groups_of(3, false).each do |group|
  -#   .row
  -#     - group.each do |artwork|
  -#       .col-md-4
  -#         = link_to image_tag(attachment_url(img, :file), class: 'image-responsive'),
  -#           artwork_path(artwork)
  -#       %br/

app/views/artworks/new.html.haml
%h1 Create a New Artwork Listing
%br/
.col-md-8
  = form_for @artwork do |f|
    = form_group_tag(@artwork.errors[:title]) do
      = f.label :title
      = f.text_field :title, class: 'form-control',
        placeholder: "Enter the title of your piece here"

    = form_group_tag(@artwork.errors[:category]) do
      = f.label :category
      = f.text_field :category_list, class: 'form-control',
        placeholder: "Enter categories e.g. Landscapes, separated by commas"

    = form_group_tag(@artwork.errors[:description]) do
      = f.label :description
      = f.text_area :description, rows: 4, class: 'form-control',
        placeholder:  "Enter a brief description of your piece here"

    = form_group_tag(@artwork.errors[:price]) do
      = f.label :price
      = f.number_field :price, class: 'form-control form-narrow',
        placeholder: "Enter a price in USD here"

    = form_group_tag(@artwork.errors[:discount]) do
      = f.label :discount
      = f.number_field :discount, class: 'form-control form-narrow',
        placeholder: "Enter an optional discount % here"

    %h3 Images
    #images
      = f.fields_for :images do |image|
        = render 'shared/image_fields', f: image
      .links
        = link_to_add_association 'add image', f, :images, partial: 'shared/image_fields'
    %br/
    = f.submit "Save", class: 'btn btn-success'

app/views/artworks/show.html.haml
%br/
%center
  - @artwork.images.each do |img|
    = image_tag(attachment_url(img, :file, :fit, 400, 400))

%h1= @artwork.title
%h3= @artwork.category_list
%p=  @artwork.description
%p=  number_to_currency(@artwork.price)

= link_to "Edit your Listing", edit_artwork_path, class: 'btn btn-primary'
= link_to "Make a new Listing", new_artwork_path, class: 'btn btn-primary'
= link_to "Buy it!", new_purchase_path(id: @artwork.id), class: 'btn btn-primary'
- if current_user
  = render partial: 'shared/favorite', locals: { favoritable: @artwork, favorited: @favorited }

app/views/profiles/edit.html.haml
%h1 Edit your Profile page
%br/
%center
  .list-group#draggableList
    - @profile.images.each do |img|
      .list-group-item
        = image_tag(attachment_url(img, :file, :fit, 400, 400))
        %span{ class: 'ion-arrow-move', 'aria-hidden' => 'true' }
        
.col-md-8
  = form_for @profile do |f|

    = form_group_tag(@profile.errors[:name]) do
      = f.label :name
      = f.text_field :name, class: 'form-control',
        placeholder: "Enter your name here"

    = form_group_tag(@profile.errors[:tagline]) do
      = f.label :tagline
      = f.text_field :tagline, class: 'form-control',
        placeholder: "Enter a 1-line description"

    = form_group_tag(@profile.errors[:statement]) do
      = f.label :statement
      = f.text_area :statement, rows: 8, class: 'form-control',
        placeholder: "Enter your Artist's Statement here"

    = form_group_tag(@profile.errors[:info]) do
      = f.label :info
      = f.text_area :info, rows: 12, class: 'form-control',
        placeholder: "Write anything you like here"

    %h3 Images
    #images
      = f.fields_for :images do |image|
        = render 'shared/image_fields', f: image
      .links
        = link_to_add_association 'add image', f, :images, partial: 'shared/image_fields'
    %br/
    = f.submit "Save", class: 'btn btn-success'

app/views/profiles/index.html.haml
%h1 Discover Artists on Easel
%br/
- @profiles.each do |profile|
  .row
    .col-md-3
      = image_tag(attachment_url(profile.images.first, :file, :fit, 200, 200 ), class: 'image-responsive')
    .media-heading
      .col-md-2
        %h4= link_to profile.name, profile_path(profile)
      .col-md-4
        %h5= profile.tagline
  %br/

-# %center
-#   - @artworks.each do |artwork|
-#     = link_to image_tag(attachment_url(artwork.images.first, :file, :fill, 200, 200),
-#       class: 'image-responsive'), artwork_path(artwork)

app/views/profiles/new.html.haml
%h1 Create your Profile page
%br/
.col-md-8
  = form_for @profile do |f|

    = form_group_tag(@profile.errors[:name]) do
      = f.label :name
      = f.text_field :name, class: 'form-control',
        placeholder: "Enter your name here"

    = form_group_tag(@profile.errors[:tagline]) do
      = f.label :tagline
      = f.text_field :tagline, class: 'form-control',
        placeholder: "Enter a 1-line description"

    = form_group_tag(@profile.errors[:statement]) do
      = f.label :statement
      = f.text_area :statement, rows: 8, class: 'form-control',
        placeholder: "Enter your Artist's Statement here"

    = form_group_tag(@profile.errors[:info]) do
      = f.label :info
      = f.text_area :info, rows: 12, class: 'form-control',
        placeholder: "Write anything you like here"

    %h3 Images
    #images
      = f.fields_for :images do |image|
        = render 'shared/image_fields', f: image
      .links
        = link_to_add_association 'add image', f, :images, partial: 'shared/image_fields'
    %br/
    = f.submit "Save", class: 'btn btn-success'

app/views/profiles/show.html.haml
%br/
%center
  - @profile.images.each do |img|
    = image_tag(attachment_url(img, :file, :fit, 300, 300))

%h1= @profile.name
%h3= @profile.tagline
%p=  @profile.statement
%p=  @profile.info

= link_to "Edit your Profile", edit_profile_path, class: 'btn btn-primary'
- if current_user
  = render partial: 'shared/favorite', locals: { favoritable: @profile, favorited: @favorited }