config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :profiles

  resources :artworks

  resources :images, only: [:create, :update, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :purchases, only: [:new, :create]

  resources :refunds, only: [:create]

  resources :dashboards, only: :show

  authenticated :user do
    root 'dashboards#show', as: :authenticated_root # change root for signed-in users
  end

  get 'welcome/about'

  root 'welcome#index'

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :user
  has_many :purchases
  has_many :favorites, dependent: :destroy
  has_many :images, -> {order(position: :asc)}, as: :imageable, dependent: :destroy
  # accepts_attachments_for :images, attachment: :file, append: true
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true

  def category_list
    category.join(', ')
  end

  def category_list=(category)
    self.category = category.split(',')
  end
end

app/models/dashboard.rb
class Dashboard

  def initialize(user)
    @user = user
  end

  def listed_artworks
    @user.artworks.all
  end

  def purchased_artworks
    @user.purchased_artworks.all
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  attachment :file
  acts_as_list scope: :imageable
  # default_scope { order(:position) }
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :favorites, as: :favoritable, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :artwork
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]

  has_one :profile
  has_many :artworks
  has_many :purchases
  has_many :purchased_artworks, through: :purchases, source: :artwork
  has_many :favorites, dependent: :destroy

  # def favorite_for(favoritable)
  #   favorites.where(favoritable_id: favoritable.id).first
  # end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def update
    # use 'acts_as_list' gem helper 'insert_at' to update image position
    image = Image.find(params[:id])
    image.insert_at(params[:image][:position].to_i)
    redirect_to :back
  end
end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController

  def create
    # binding.pry
    @purchase = Purchase.find(params[:purchase_id])
    Stripe::Refund.create(charge: @purchase.charge_id)
    @purchase.update(refunded: true)

    flash[:notice] = "Your refund has been issued"
    redirect_to root_path

  rescue Stripe::InvalidRequestError => e
     flash[:alert] = e.message
     redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # helper method for displaying gravatar image
  def gravatar_url(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, class: "gravatar")
  end

  # helper method to display errors on forms
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def authorize_view_element
    current_user.admin? || (current_user.premium? && @wiki.user_id = current_user.id)
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/refunds_helper.rb
module RefundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title Easel
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag 'application', 'data-turbolinks-track' => true

      = stylesheet_link_tag 'http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'
      = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.4.2/Sortable.min.js'
      -# = javascript_include_tag :cocoon
      = csrf_meta_tags

  %body
    .container

      .flash
        - if flash[:notice]
          .alert.alert-success
            %button.close{"data-dismiss" => "alert", :type => "button"} &times;
            = notice
        - elsif flash[:alert]
          .alert.alert-danger
            %button.close{"data-dismiss" => "alert", :type => "button"} &times;
            = alert

      %ul.nav.nav-tabs
        %li= link_to "Home", root_path
        %li= link_to "About", welcome_about_path
        %li= link_to "Artwork", artworks_path
        %li= link_to "Artists", profiles_path
        - if user_signed_in?
          .pull-right.user-info
            = gravatar_url(current_user, 35)
            .pull-right
              = link_to current_user.username, dashboard_path(current_user), class: "navbar-link"
              %br/
              = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-link"
        - else
          %li.pull-right= link_to "Sign Up", new_user_registration_path
          %li.pull-right= link_to "Sign In", new_user_session_path

      = yield

app/views/shared/_favorite.html.haml
- if favorited
  = link_to favorite_path(favorited), class: 'btn btn-danger', method: :delete do
    %i.ion-heart-broken>
    \  Unfavorite
- else
  = link_to favorites_path(favorite: {favoritable_id: favoritable.id, favoritable_type: favoritable.class.to_s}),
    class: 'btn btn-primary', method: :post do
    %i.ion-ios-heart>
    \  Favorite

app/views/shared/_image_fields.html.haml
.nested-fields
  = f.attachment_field :file
  %br/
  = link_to_remove_association 'remove image', f
%br/